[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ElenaVillano/prope-programacion/blob/main/materiales/m05_exploracion.ipynb)

# Propedéutico de Programación para el Análisis de datos

## EGobiernoyTP

**Verano 2026**

### Material 5: Exploración de bases de datos: intro pandas

1. Series y DataFrames
   - ¿Qué es una Series?
   - ¿Qué es un DataFrame?
   - Filas, columnas e índice
2. Generalidades de bases de datos
    - ¿Cuántas variables y observaciones tenemos?
    - Diccionario de variables
3. Primera exploración
   - `head()`
   - `tail()`
   - `sample()`
   - `shape`
   - `columns`
   - `info()`
   - `describe()`
4. Seleccionar columnas
   - Una columna
   - Varias columnas
5. Tipos de datos en db
    - Cambiar tipos de datos
        - str
        - float
        - int
        - datetime


El objetivo de la exploración es aprender a **conocer los datos antes de usarlos**. 

En una base de datos tabular:

- cada fila representa una observación;
  
- cada columna representa una variable;
  
- cada celda contiene un valor.

De las primeras preguntas a responder al tener una base de datos son:

- ¿Cuál es la unidad de observación?

- ¿Cuántas observaciones tenemos?

- ¿Cuántas variables tenemos?

In [62]:
# Librerías 
import pandas as pd
import numpy as np

#### Series y DataFrames

Al trabajar con **pandas** tenemos dos estructuras:

- `Series`: estructura que contiene una secuencia de valores
    - Se puede pensar como una columna de datos
    - Que contiene un índice que identifica las posiciones de las observarciones
- `DataFrame`: estructura de datos organizada con filas y columnas

In [2]:
# Series
edades = pd.Series([25, 34, 29, 41, 22])

edades

0    25
1    34
2    29
3    41
4    22
dtype: int64

In [3]:
# DataFrame
datos = pd.DataFrame({
    "nombre": ["Ana", "Luis", "María", "Carlos", "Sofía"],
    "edad": [25, 34, 29, 41, 22],
    "estado": ["Oaxaca", "Puebla", "Jalisco", "Yucatán", "Oaxaca"],
    "ingreso": [8500, 12000, 10500, 15000, 9000]
})

datos

   nombre  edad   estado  ingreso
0     Ana    25   Oaxaca     8500
1    Luis    34   Puebla    12000
2   María    29  Jalisco    10500
3  Carlos    41  Yucatán    15000
4   Sofía    22   Oaxaca     9000

In [4]:
type(datos)

pandas.DataFrame

In [5]:
type(edades)

pandas.Series

In [6]:
datos['nombre']

0       Ana
1      Luis
2     María
3    Carlos
4     Sofía
Name: nombre, dtype: str

#### Ahora con una base de datos real

In [7]:
#from google.colab import drive
#drive.mount('/content/drive', force_remount=True)

In [209]:
#df = pd.read_csv('/content/drive/MyDrive/datos/datos.csv')
df = pd.read_csv('https://raw.githubusercontent.com/ElenaVillano/prope-programacion/refs/heads/main/data/datos.csv')

##### Dimensiones de la base

Es la primera pregunta que nos hacemos: ¿qué tan grande es la base?

`df.shape` regresa una tupla con (número de filas, número de columnas).

In [9]:
df.shape

(10404, 15)

In [10]:
# Columnas
df.shape[1]

15

In [11]:
# Renglones
df.shape[0]

10404

In [100]:
# Nombre de columnas
df.columns

Index(['Indicator', 'Group', 'State', 'Subgroup', 'Phase', 'Time Period',
       'Time Period Label', 'Time Period Start Date', 'Time Period End Date',
       'Value', 'LowCI', 'HighCI', 'Confidence Interval', 'Quartile Range',
       'Suppression Flag'],
      dtype='str')

#### Diccionario de datos

> Antes de analizar una base de datos, debemos entender qué representa cada variable.

- **Fuente:** National Center for Health Statistics (NCHS) + U.S. Census Bureau
- **Qué es:** Encuesta experimental en línea (~20 min) lanzada en abril 2020 por el Census Bureau junto con NCHS y otras agencias federales, para medir en tiempo casi real el impacto de la pandemia de COVID-19 en los hogares estadounidenses.



| Columna | Descripción |
|---|---|
| Indicator | Indicador medido (ej. "Symptoms of Anxiety Disorder") |
| Group | Categoría de desagregación (National Estimate, By Age, By Sex, By State, By Race/Hispanic ethnicity...) |
| State | Estado o "United States" (nacional) |
| Subgroup | Valor específico dentro del Group (ej. "18-29 years") |
| Phase | Fase de la encuesta (1, 2, 3, 3.1...) |
| Time Period | N° secuencial de la ronda de recolección |
| Time Period Label | Rango de fechas legible (ej. "Aug 19 - Aug 31, 2020") |
| Time Period Start Date | Fecha de inicio del periodo |
| Time Period End Date | Fecha de fin del periodo |
| Value | Estimación (%) |
| LowCI | Límite inferior del IC 95% |
| HighCI | Límite superior del IC 95% |
| Confidence Interval | IC en texto (ej. "19.0 - 19.8") |
| Quartile Range | Rango de cuartil (indicadores de vivienda/gasto) |
| Suppression Flag | Marca de supresión por baja fiabilidad estadística |

In [13]:
df.head()

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
0,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Male,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,6.9,6.5,7.3,6.5 - 7.3,NaN,NaN
1,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Female,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,11.0,10.4,11.6,10.4 - 11.6,NaN,NaN
2,Needed Counseling or Therapy But Did Not Get I...,By Sex,United States,Female,-1,1,"Dec 22, 2020 - Jan 5, 2021",12/22/2020,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN
3,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN
4,Took Prescription Medication for Mental Health...,By Age,United States,60 - 69 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN

#### 2. Primera vista: ¿cómo se ven los datos?

`.head()` muestra las primeras filas. Es lo primero que se hace al abrir cualquier base de datos.

In [14]:
df.head(3)

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
0,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Male,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,6.9,6.5,7.3,6.5 - 7.3,NaN,NaN
1,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Female,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,11.0,10.4,11.6,10.4 - 11.6,NaN,NaN
2,Needed Counseling or Therapy But Did Not Get I...,By Sex,United States,Female,-1,1,"Dec 22, 2020 - Jan 5, 2021",12/22/2020,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.tail()

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
10399,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,Virginia,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,10.1,7.1,13.8,7.1 - 13.8,9.6-11.3,NaN
10400,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,Washington,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,14.8,12.5,17.4,12.5 - 17.4,13.0-20.8,NaN
10401,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,West Virginia,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,9.8,6.6,13.8,6.6 - 13.8,9.6-11.3,NaN
10402,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,Wisconsin,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,11.6,8.5,15.3,8.5 - 15.3,11.4-12.9,NaN
10403,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,11.5,8.6,15.1,8.6 - 15.1,11.4-12.9,NaN

In [16]:
df.sample(10)

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
8227,Needed Counseling or Therapy But Did Not Get I...,By State,Alaska,Alaska,3.2,39,"Sep 29 - Oct 11, 2021",09/29/2021,10/11/2021,11.9,9.3,14.8,9.3 - 14.8,11.0-12.1,NaN
7688,Took Prescription Medication for Mental Health...,By State,Michigan,Michigan,3.2,38,"Sep 15 - Sep 27, 2021",09/15/2021,09/27/2021,23.3,20.0,26.9,20.0 - 26.9,21.4-24.3,NaN
8653,Needed Counseling or Therapy But Did Not Get I...,By State,Iowa,Iowa,3.3,40,"Dec 1 - Dec 13, 2021",12/01/2021,12/13/2021,12.1,9.8,14.8,9.8 - 14.8,11.3-12.5,NaN
1413,Needed Counseling or Therapy But Did Not Get I...,By State,Idaho,Idaho,2,17,"Oct 14 - Oct 26, 2020",10/14/2020,10/26/2020,10.0,8.2,12.1,8.2 - 12.1,9.4-10.0,NaN
4948,Took Prescription Medication for Mental Health...,By Sex,United States,Male,3.1,29,"Apr 28 - May 10, 2021",04/28/2021,05/10/2021,18.8,18.0,19.7,18.0 - 19.7,NaN,NaN
5095,Took Prescription Medication for Mental Health...,By Age,United States,80 years and above,3.1,30,"May 12 - May 24, 2021",05/12/2021,05/24/2021,15.2,11.7,19.4,11.7 - 19.4,NaN,NaN
8976,Needed Counseling or Therapy But Did Not Get I...,By State,Kentucky,Kentucky,3.3,41,"Dec 29, 2021 - Jan 10, 2022",12/29/2021,01/10/2022,10.6,7.7,14.0,7.7 - 14.0,10.2-11.6,NaN
6961,Needed Counseling or Therapy But Did Not Get I...,By State,Iowa,Iowa,3.2,35,"Aug 4 - Aug 16, 2021",08/04/2021,08/16/2021,9.0,6.4,12.2,6.4 - 12.2,6.6-9.0,NaN
3786,Needed Counseling or Therapy But Did Not Get I...,By Race/Hispanic ethnicity,United States,"Non-Hispanic White, single race",3 (Jan 6 – Mar 29),25,"Feb 17 - Mar 1, 2021",02/17/2021,03/01/2021,11.4,10.8,12.0,10.8 - 12.0,NaN,NaN
2282,Needed Counseling or Therapy But Did Not Get I...,By State,Idaho,Idaho,3 (Oct 28 – Dec 21),20,"Nov 25 - Dec 7, 2020",11/25/2020,12/07/2020,12.5,9.4,16.2,9.4 - 16.2,11.7-12.9,NaN

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10404 entries, 0 to 10403
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Indicator               10404 non-null  str
 1   Group                   10404 non-null  str
 2   State                   10404 non-null  str
 3   Subgroup                10404 non-null  str
 4   Phase                   10404 non-null  str
 5   Time Period             10404 non-null  int64
 6   Time Period Label       10404 non-null  str
 7   Time Period Start Date  10404 non-null  str
 8   Time Period End Date    10404 non-null  str
 9   Value                   9914 non-null   float64
 10  LowCI                   9914 non-null   float64
 11  HighCI                  9914 non-null   float64
 12  Confidence Interval     9914 non-null   str
 13  Quartile Range          6732 non-null   str
 14  Suppression Flag        22 non-null     float64
dtypes: float64(4), int64(1), str(10)
memory usage: 1.2 MB

#### Selección de variables

In [23]:
df[['Indicator','Group']].sample(5)

                                              Indicator     Group
1721  Needed Counseling or Therapy But Did Not Get I...  By State
6577  Needed Counseling or Therapy But Did Not Get I...    By Age
3963       Received Counseling or Therapy, Last 4 Weeks  By State
7154       Received Counseling or Therapy, Last 4 Weeks  By State
3494  Needed Counseling or Therapy But Did Not Get I...    By Sex

In [47]:
df['Group'].value_counts()

Group
By State                                         6732
By Age                                           1064
By Race/Hispanic ethnicity                        760
By Education                                      608
By Sex                                            304
By Presence of Symptoms of Anxiety/Depression     304
By Disability status                              168
By Sexual orientation                             156
By Gender identity                                156
National Estimate                                 152
Name: count, dtype: int64

In [49]:
df['State'].nunique()

52

In [53]:
df['State'].unique()

<StringArray>
[       'United States',              'Alabama',               'Alaska',
              'Arizona',             'Arkansas',           'California',
             'Colorado',          'Connecticut',             'Delaware',
 'District of Columbia',              'Florida',              'Georgia',
               'Hawaii',                'Idaho',             'Illinois',
              'Indiana',                 'Iowa',               'Kansas',
             'Kentucky',            'Louisiana',                'Maine',
             'Maryland',        'Massachusetts',             'Michigan',
            'Minnesota',          'Mississippi',             'Missouri',
              'Montana',             'Nebraska',               'Nevada',
        'New Hampshire',           'New Jersey',           'New Mexico',
             'New York',       'North Carolina',         'North Dakota',
                 'Ohio',             'Oklahoma',               'Oregon',
         'Pennsylvania',         'Rhode Island',       'South Carolina',
         'South Dakota',            'Tennessee',                'Texas',
                 'Utah',              'Vermont',             'Virginia',
           'Washington',        'West Virginia',            'Wisconsin',
              'Wyoming']
Length: 52, dtype: str

In [71]:
df['Subgroup'].mode()

0                                         18 - 29 years
1                                         30 - 39 years
2                                         40 - 49 years
3                                         50 - 59 years
4                                         60 - 69 years
5                                         70 - 79 years
6                                    80 years and above
7                           Bachelor's degree or higher
8     Did not experience symptoms of anxiety/depress...
9     Experienced symptoms of anxiety/depression in ...
10                                               Female
11                           High school diploma or GED
12                                   Hispanic or Latino
13                      Less than a high school diploma
14                                                 Male
15                      Non-Hispanic Asian, single race
16                      Non-Hispanic Black, single race
17                      Non-Hispanic White, single race
18         Non-Hispanic, other races and multiple races
19                      Some college/Associate's degree
20                                        United States
Name: Subgroup, dtype: str

In [149]:
df['Subgroup'].value_counts()

Subgroup
Male                                                                     152
Female                                                                   152
50 - 59 years                                                            152
60 - 69 years                                                            152
70 - 79 years                                                            152
80 years and above                                                       152
40 - 49 years                                                            152
United States                                                            152
18 - 29 years                                                            152
30 - 39 years                                                            152
Did not experience symptoms of anxiety/depression in the past 4 weeks    152
Experienced symptoms of anxiety/depression in past 4 weeks               152
Hispanic or Latino                                                       152
Non-Hispanic White, single race                                          152
Non-Hispanic Black, single race                                          152
Non-Hispanic Asian, single race                                          152
Non-Hispanic, other races and multiple races                             152
Less than a high school diploma                                          152
High school diploma or GED                                               152
Some college/Associate's degree                                          152
Bachelor's degree or higher                                              152
Alabama                                                                  132
Alaska                                                                   132
Arizona                                                                  132
Arkansas                                                                 132
California                                                               132
Colorado                                                                 132
Connecticut                                                              132
Delaware                                                                 132
District of Columbia                                                     132
Florida                                                                  132
Georgia                                                                  132
Hawaii                                                                   132
Idaho                                                                    132
Illinois                                                                 132
Indiana                                                                  132
Iowa                                                                     132
Kansas                                                                   132
Kentucky                                                                 132
Louisiana                                                                132
Maine                                                                    132
Maryland                                                                 132
Massachusetts                                                            132
Michigan                                                                 132
Minnesota                                                                132
Mississippi                                                              132
Missouri                                                                 132
Montana                                                                  132
Nebraska                                                                 132
Nevada                                                                   132
New Hampshire                                                            132
New Jersey                                                               132
New Mexico                                                               132
New York                                                                 132
North Carolina                                                           132
North Dakota                                                             132
Ohio                                                                     132
Oklahoma                                                                 132
Oregon                                                                   132
Pennsylvania                                                             132
Rhode Island                                                             132
South Carolina                                                           132
South Dakota                                                             132
Tennessee                                                                132
Texas                                                                    132
Utah                                                                     132
Vermont                                                                  132
Virginia                                                                 132
Washington                                                               132
West Virginia                                                            132
Wisconsin                                                                132
Wyoming                                                                  132
With disability                                                           84
Without disability                                                        84
Bisexual                                                                  52
Cis-gender male                                                           52
Cis-gender female                                                         52
Transgender                                                               52
Gay or lesbian                                                            52
Straight                                                                  52
Name: count, dtype: int64

In [ ]:
# Proporción de categorías
prop = df['entidad'].value_counts(normalize=True)

In [ ]:
# Lo visualizamos mejor:
pd.concat([conteos,prop], # observa que aquí estamos concatenando las dos columnas antes creadas 
          keys=['num','prop'], 
          axis=1)

In [211]:
# Para ver 200 filas en el notebook
pd.set_option('display.max_rows', 200)
#Para ver 10 columnas en el notebook
pd.set_option('display.max_columns', 20)

In [74]:
df['Subgroup'].value_counts()

Subgroup
Male                                                                     152
Female                                                                   152
50 - 59 years                                                            152
60 - 69 years                                                            152
70 - 79 years                                                            152
80 years and above                                                       152
40 - 49 years                                                            152
United States                                                            152
18 - 29 years                                                            152
30 - 39 years                                                            152
Did not experience symptoms of anxiety/depression in the past 4 weeks    152
Experienced symptoms of anxiety/depression in past 4 weeks               152
Hispanic or Latino                                                       152
Non-Hispanic White, single race                                          152
Non-Hispanic Black, single race                                          152
Non-Hispanic Asian, single race                                          152
Non-Hispanic, other races and multiple races                             152
Less than a high school diploma                                          152
High school diploma or GED                                               152
Some college/Associate's degree                                          152
Bachelor's degree or higher                                              152
Alabama                                                                  132
Alaska                                                                   132
Arizona                                                                  132
Arkansas                                                                 132
California                                                               132
Colorado                                                                 132
Connecticut                                                              132
Delaware                                                                 132
District of Columbia                                                     132
Florida                                                                  132
Georgia                                                                  132
Hawaii                                                                   132
Idaho                                                                    132
Illinois                                                                 132
Indiana                                                                  132
Iowa                                                                     132
Kansas                                                                   132
Kentucky                                                                 132
Louisiana                                                                132
Maine                                                                    132
Maryland                                                                 132
Massachusetts                                                            132
Michigan                                                                 132
Minnesota                                                                132
Mississippi                                                              132
Missouri                                                                 132
Montana                                                                  132
Nebraska                                                                 132
Nevada                                                                   132
New Hampshire                                                            132
New Jersey                                                               132
New Mexico                                                               132
New York                                                                 132
North Carolina                                                           132
North Dakota                                                             132
Ohio                                                                     132
Oklahoma                                                                 132
Oregon                                                                   132
Pennsylvania                                                             132
Rhode Island                                                             132
South Carolina                                                           132
South Dakota                                                             132
Tennessee                                                                132
Texas                                                                    132
Utah                                                                     132
Vermont                                                                  132
Virginia                                                                 132
Washington                                                               132
West Virginia                                                            132
Wisconsin                                                                132
Wyoming                                                                  132
With disability                                                           84
Without disability                                                        84
Bisexual                                                                  52
Cis-gender male                                                           52
Cis-gender female                                                         52
Transgender                                                               52
Gay or lesbian                                                            52
Straight                                                                  52
Name: count, dtype: int64

#### Tipos de variables

Determinar el tipo de variables de las columnas dirigirá en gran medida el análisis de datos.

Cuatro tipos de variables:

| Tipo | Descripción | Ejemplos en esta base ? |
|---|---|---|
| **Numéricas** | Valores numéricos (enteros o decimales) | |
| **Categóricas** | Categorías o grupos | |
| **Temporales** | Fechas o periodos de tiempo | |
| **Texto libre** | Texto sin estructura fija | |

Pandas detecta automáticamente algunos tipos con `.dtypes`:

In [75]:
# dtypes muestra el tipo de dato que pandas asignó a cada columna
# object = texto,  int64 = entero,  float64 = decimal
df.dtypes

Indicator                     str
Group                         str
State                         str
Subgroup                      str
Phase                         str
Time Period                 int64
Time Period Label             str
Time Period Start Date        str
Time Period End Date          str
Value                     float64
LowCI                     float64
HighCI                    float64
Confidence Interval           str
Quartile Range                str
Suppression Flag          float64
dtype: object

#### OJO aquí es tu trabajo determinar qué tipo de variables deben de ser

- ¿Cuáles crees que deben de ser categóricas que Python detectó como numéricas?

- ¿Cuáles crees que son categóricas que no deberían de serlo?

In [76]:
# Variables numéricas: pandas las detecta como int o float
vars_numericas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Variables categóricas: pandas las detecta como 'str' 
vars_categoricas = df.select_dtypes(include='str').columns.tolist()

In [81]:
vars_categoricas

['Indicator',
 'Group',
 'State',
 'Subgroup',
 'Phase',
 'Time Period Label',
 'Time Period Start Date',
 'Time Period End Date',
 'Confidence Interval',
 'Quartile Range']

In [80]:
vars_numericas

['Time Period', 'Value', 'LowCI', 'HighCI', 'Suppression Flag']

#### Variables categóricas

En lugar de hacer un análisis para cada variable categórica, por separado hacemos un análisis de varias variables para revisarlas con más detalle.

Para variables categóricas nos interesa saber: ¿cuántas categorías hay? ¿cuál es la más frecuente? ¿están balanceadas o muy desiguales?

In [96]:
def analizar_categoricas(df, columnas):
    """Genera un resumen de variables categóricas."""

    resultados = []

    for columna in columnas:

        frecuencias = df[columna].value_counts()

        resultado = {
            "variable": columna,
            "n_categorias": df[columna].nunique(),
            "n_faltantes": df[columna].isnull().sum(),
            "moda": frecuencias.index[0],
            "top_2": frecuencias.index[1] if len(frecuencias) > 1 else "-",
            "top_3": frecuencias.index[2] if len(frecuencias) > 2 else "-"
        }

        resultados.append(resultado)

    return pd.DataFrame(resultados)

In [114]:
analizar_categoricas(df, vars_categoricas)

,variable,n_categorias,n_faltantes,moda,top_2,top_3
0,Indicator,4,0,"Received Counseling or Therapy, Last 4 Weeks",Needed Counseling or Therapy But Did Not Get I...,Took Prescription Medication for Mental Health...
1,Group,10,0,By State,By Age,By Race/Hispanic ethnicity
2,State,52,0,United States,Alabama,Alaska
3,Subgroup,80,0,Male,Female,50 - 59 years
4,Phase,8,0,3.2,3.1,3 (Jan 6 – Mar 29)
5,Time Period Label,38,0,"Jul 21 - Aug 2, 2021","Aug 4 - Aug 16, 2021","Aug 18 - Aug 30, 2021"
6,Time Period Start Date,38,0,07/21/2021,08/04/2021,08/18/2021
7,Time Period End Date,38,0,08/02/2021,08/16/2021,08/30/2021
8,Confidence Interval,7709,490,9.1 - 13.6,6.7 - 10.7,7.2 - 12.0
9,Quartile Range,500,3672,9.8-11.2,4.8-8.6,9.6-11.2

In [117]:
df['Phase'].value_counts()
#df['Phase'].value_counts().index[0]
#df['Phase'].value_counts().index[1]

Phase
3.2                    1920
3.1                    1776
3 (Jan 6 – Mar 29)     1728
2                      1440
3 (Oct 28 – Dec 21)    1152
3.3                     960
3.4                     960
-1                      468
Name: count, dtype: int64

#### Variables numéricas

Para las numéricas nos interesa saber: ¿cuál es el rango? ¿hay valores extremos? ¿cómo está distribuida?


**¿Qué buscamos en esta tabla?**

- **Media vs. mediana muy diferentes** → indica valores extremos (outliers). Por ejemplo, si la media de `consumo_total` es mucho mayor que la mediana, hay colonias con consumo excepcionalmente alto que "jalan" el promedio hacia arriba.
- **Desviación estándar muy grande** → los datos están muy dispersos.
- **Mínimo = 0** en columnas de consumo → colonias sin consumo registrado.
- **`anio` con desv_estandar = 0** → todos los registros son del mismo año (2019).

In [128]:
df[vars_numericas].describe()

        Time Period        Value        LowCI       HighCI  Suppression Flag
count  10404.000000  9914.000000  9914.000000  9914.000000              22.0
mean      28.134948    17.450736    14.771565    20.475661               1.0
std       11.040210     8.270565     7.659396     9.052521               0.0
min        1.000000     1.400000     0.800000     2.000000               1.0
25%       20.000000    10.300000     8.000000    12.900000               1.0
50%       29.000000    16.200000    13.900000    19.200000               1.0
75%       37.000000    24.000000    20.800000    27.400000               1.0
max       45.000000    62.900000    53.200000    71.900000               1.0

In [125]:
df.columns

Index(['Indicator', 'Group', 'State', 'Subgroup', 'Phase', 'Time Period',
       'Time Period Label', 'Time Period Start Date', 'Time Period End Date',
       'Value', 'LowCI', 'HighCI', 'Confidence Interval', 'Quartile Range',
       'Suppression Flag'],
      dtype='str')

#### Variables temporales

Detectar variables temporales requiere un análisis un poco más detallado de la información. Python no siempre logra detectar variables temporales correctamente y usualmente ustedes tendrán que trabajar en detectarlas. 

Si no están en el formato correcto:
- **No puedes restarlas** para calcular duración
- **No puedes ordenarlas** correctamente (el orden de texto es alfabético, no cronológico)
- **No puedes graficarlas** en un eje de tiempo

Antes de convertir, necesitamos saber el formato. Los más comunes son:

| Ejemplo en los datos | Formato pandas |
|---|---|
| `2021-03-15` | `'%Y-%m-%d'` |
| `15/03/2021` | `'%d/%m/%Y'` |
| `03/15/2021` | `'%m/%d/%Y'` |
| `March 15, 2021` | `'%B %d, %Y'` |
| `15-Mar-2021` | `'%d-%b-%Y'` |

##### 8.1. Convertir a datetime — `pd.to_datetime()`

`pd.to_datetime()` es la función de pandas para convertir texto en fechas reales.  
Una vez convertidas, el tipo de dato será **`datetime64[ns]`** — el formato de fecha de pandas.

Conversión automática (cuando el formato es estándar)

In [156]:
df.dtypes

Indicator                            str
Group                                str
State                                str
Subgroup                             str
Phase                                str
Time Period                        int64
Time Period Label          datetime64[s]
Time Period Start Date    datetime64[us]
Time Period End Date      datetime64[us]
Value                            float64
LowCI                            float64
HighCI                           float64
Confidence Interval                  str
Quartile Range                       str
Suppression Flag                 float64
dtype: object

In [157]:
df[['Time Period','Time Period Label', 'Time Period Start Date', 'Time Period End Date']].sample(10, random_state=123)

,Time Period,Time Period Label,Time Period Start Date,Time Period End Date
3833,25,NaT,2021-02-17,2021-03-01
6919,35,NaT,2021-08-04,2021-08-16
2585,21,NaT,2020-12-09,2020-12-21
2131,20,NaT,2020-11-25,2020-12-07
2265,20,NaT,2020-11-25,2020-12-07
4008,26,NaT,2021-03-03,2021-03-15
7428,37,NaT,2021-09-01,2021-09-13
5247,30,NaT,2021-05-12,2021-05-24
257,13,NaT,2020-08-19,2020-08-31
7360,37,NaT,2021-09-01,2021-09-13

In [158]:
# Si las fechas vienen en formato ISO (YYYY-MM-DD), pandas las detecta solas
# errors='coerce' convierte los valores que no pueda parsear en NaT (Not a Time)
# en lugar de lanzar un error — útil para detectar fechas mal formateadas
df['Time Period Start Date'] = pd.to_datetime(df['Time Period Start Date'] , errors='coerce')
df['Time Period End Date'] = pd.to_datetime(df['Time Period End Date'] , errors='coerce')

In [159]:
df.dtypes

Indicator                            str
Group                                str
State                                str
Subgroup                             str
Phase                                str
Time Period                        int64
Time Period Label          datetime64[s]
Time Period Start Date    datetime64[us]
Time Period End Date      datetime64[us]
Value                            float64
LowCI                            float64
HighCI                           float64
Confidence Interval                  str
Quartile Range                       str
Suppression Flag                 float64
dtype: object

In [155]:
print("--- Rango de Fechas ---")
min_date = df['Time Period Start Date'].min()
max_date = df['Time Period End Date'].max()
print(f"Fecha mínima: {min_date}")
print(f"Fecha máxima: {max_date}")

--- Rango de Fechas ---
Fecha mínima: 2020-08-19 00:00:00
Fecha máxima: 2022-05-09 00:00:00

### 8.2 Extraer componentes de la fecha

Una vez que la columna es `datetime`, podemos extraer partes de la fecha con el **accessor `.dt`**.  
Es como abrir la fecha y sacar lo que nos interesa.

| Accessor | Qué devuelve | Rango típico |
|---|---|---|
| `.dt.year` | Año | 2015, 2016... |
| `.dt.month` | Número de mes | 1–12 |
| `.dt.month_name()` | Nombre del mes | 'January'... |
| `.dt.day` | Día del mes | 1–31 |
| `.dt.day_of_week` | Día de la semana | 0=lunes, 6=domingo |
| `.dt.day_name()` | Nombre del día | 'Monday'... |
| `.dt.quarter` | Trimestre | 1–4 |
| `.dt.is_month_start` | ¿Es el primer día del mes? | True/False |

In [208]:
## Extraemos componentes útiles de la fecha de inicio
#df['anio_inicio']     = df['Time Period Start Date'].dt.year
#df['mes_inicio']      = df['Time Period Start Date'].dt.month
#df['nombre_mes']      = df['Time Period Start Date'].dt.month_name()  # Nombre en inglés
#df['trimestre']       = df['Time Period Start Date'].dt.quarter
#df['dia_semana']      = df['Time Period Start Date'].dt.day_name()#

## Vista de los nuevos componentes
#df[['Time Period Start Date', 'anio_inicio', 'mes_inicio', 'nombre_mes', 'trimestre', 'dia_semana']].head(8)

In [170]:
df['Value'].value_counts().head(20)

Value
9.5     99
9.9     85
10.6    84
11.2    84
10.4    83
9.8     80
9.3     79
9.4     77
9.2     77
10.7    77
10.1    76
9.0     76
8.6     75
9.1     74
10.3    73
9.7     73
10.9    72
11.0    71
10.0    71
10.8    71
Name: count, dtype: int64

#### Cambio de tipo de variables de str a numeric o viceversa

In [175]:
# Hacer una variable numérica una categórica
df['Value'] = df['Value'].astype('str')

In [174]:
df.dtypes

Indicator                            str
Group                                str
State                                str
Subgroup                             str
Phase                                str
Time Period                        int64
Time Period Label          datetime64[s]
Time Period Start Date    datetime64[us]
Time Period End Date      datetime64[us]
Value                                str
LowCI                            float64
HighCI                           float64
Confidence Interval                  str
Quartile Range                       str
Suppression Flag                 float64
anio_inicio                        int32
mes_inicio                         int32
nombre_mes                           str
trimestre                          int32
dia_semana                           str
dtype: object

In [179]:
# Hacer una variable categórica una numérica
df['Value'] = df['Value'].astype('int64')
#df['Value'] = df['Value'].astype('float64')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [180]:
# Otra manera de hacer la variable numérica 
df['Value'] = pd.to_numeric(df['Value'], errors='coerce', downcast='float')

#### Valores faltantes

Los NA (_not applicable, not available, not assessed, no answer_) así como los valores faltantes son comunes en bases de datos, y el manejo de ellos depende de muchos factores. Antes de hacer cualquier operación sobre los datos, debes entender el contexto de la base y qué significa cada NA o valor vacío en las columnas en las que aparece.

Algunas preguntas que debes hacerte:

* ¿Tiene sentido que estos datos no estén disponibles o no existan? (e.g., alguien que nació sin útero podría tener NA/vacío en una columna llamada "embarazos previos", y sería correcto)
* Si hay datos verdaderamente faltantes, ¿es al azar, o hay grupos más afectados? (e.g. muchos indicadores socioeconómicos no están medidos en zonas rurales, lo cual significa que cualquier análisis o modelo sería menos preciso para ellas)
* ¿Son pocos o muchos? En una columna, si nos faltan solamente unos pocos valores, tal vez vale la pena explorar métodos de imputación, pero si existen 90% de faltantes, probablemente sea mejor descartarla para análisis.

- Un dato faltante puede aparecer representado de distintas maneras (`None`, `NaN`, `pd.NA`).

In [191]:
df.isna().sum()  # Hace la suma de NAs por columna

Indicator                     0
Group                         0
State                         0
Subgroup                      0
Phase                         0
Time Period                   0
Time Period Label         10404
Time Period Start Date        0
Time Period End Date          0
Value                       490
LowCI                       490
HighCI                      490
Confidence Interval         490
Quartile Range             3672
Suppression Flag          10382
anio_inicio                   0
mes_inicio                    0
nombre_mes                    0
trimestre                     0
dia_semana                    0
dtype: int64

In [192]:
# Conteo de valores faltantes por columna
faltantes = df.isna().sum()

# También calculamos el porcentaje
pct_faltantes = (faltantes / len(df) * 100).round(2)

# Unimos en una tabla y filtramos solo las que sí tienen faltantes
tabla_faltantes = pd.DataFrame({
    'valores_faltantes': faltantes,
    'porcentaje_%': pct_faltantes
})


tabla_faltantes[tabla_faltantes['valores_faltantes'] > 0]

                     valores_faltantes  porcentaje_%
Time Period Label                10404        100.00
Value                              490          4.71
LowCI                              490          4.71
HighCI                             490          4.71
Confidence Interval                490          4.71
Quartile Range                    3672         35.29
Suppression Flag                 10382         99.79

#### Filtrado de datos

In [215]:
df["LowCI"].isna()

0        False
1        False
2         True
3         True
4         True
         ...
10399    False
10400    False
10401    False
10402    False
10403    False
Name: LowCI, Length: 10404, dtype: bool

In [217]:
df[df["LowCI"].isna()]

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
2,Needed Counseling or Therapy But Did Not Get I...,By Sex,United States,Female,-1,1,"Dec 22, 2020 - Jan 5, 2021",12/22/2020,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN
3,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN
4,Took Prescription Medication for Mental Health...,By Age,United States,60 - 69 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN
5,Took Prescription Medication for Mental Health...,By Age,United States,70 - 79 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN
6,Took Prescription Medication for Mental Health...,By Age,United States,80 years and above,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9680,Needed Counseling or Therapy But Did Not Get I...,By Education,United States,Some college/Associate's degree,-1,1,"Feb 23 - Mar 1, 2022",02/23/2022,03/01/2022,NaN,NaN,NaN,NaN,NaN,NaN
9681,Needed Counseling or Therapy But Did Not Get I...,By Education,United States,Bachelor's degree or higher,-1,1,"Feb 23 - Mar 1, 2022",02/23/2022,03/01/2022,NaN,NaN,NaN,NaN,NaN,NaN
9682,Needed Counseling or Therapy But Did Not Get I...,By Disability status,United States,With disability,-1,1,"Feb 23 - Mar 1, 2022",02/23/2022,03/01/2022,NaN,NaN,NaN,NaN,NaN,NaN
9683,Needed Counseling or Therapy But Did Not Get I...,By Disability status,United States,Without disability,-1,1,"Feb 23 - Mar 1, 2022",02/23/2022,03/01/2022,NaN,NaN,NaN,NaN,NaN,NaN
10011,Needed Counseling or Therapy But Did Not Get I...,By Age,United States,80 years and above,3.4,44,"Mar 30 - Apr 11, 2022",03/30/2022,04/11/2022,NaN,NaN,NaN,NaN,NaN,1.0

In [219]:
df['State'][df["LowCI"].isna()]

2        United States
3        United States
4        United States
5        United States
6        United States
             ...
9680     United States
9681     United States
9682     United States
9683     United States
10011    United States
Name: State, Length: 490, dtype: str

In [225]:
df['State'][df["LowCI"].isna()].value_counts()

State
United States    481
Vermont            3
Wyoming            3
North Dakota       2
Hawaii             1
Name: count, dtype: int64

Combinar condiciones con AND (&)

In [235]:
df[df["LowCI"].isna() & (df["State"] == "Vermont")]

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
5674,Needed Counseling or Therapy But Did Not Get I...,By State,Vermont,Vermont,3.1,31,"May 26 - Jun 7, 2021",05/26/2021,06/07/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
5970,Needed Counseling or Therapy But Did Not Get I...,By State,Vermont,Vermont,3.1,32,"Jun 9 - Jun 21, 2021",06/09/2021,06/21/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7631,Needed Counseling or Therapy But Did Not Get I...,By State,Vermont,Vermont,3.2,37,"Sep 1 - Sep 13, 2021",09/01/2021,09/13/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0

In [243]:
df_na= df[df["LowCI"].isna()]

Combinar condiciones con OR

In [248]:
df_na[(df_na['State']== 'Hawaii') |(df_na['State']== 'Wyoming')  ]

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
5679,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.1,31,"May 26 - Jun 7, 2021",05/26/2021,06/07/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
6232,Needed Counseling or Therapy But Did Not Get I...,By State,Hawaii,Hawaii,3.1,33,"Jun 23 - Jul 5, 2021",06/23/2021,07/05/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
6836,"Received Counseling or Therapy, Last 4 Weeks",By State,Wyoming,Wyoming,3.2,35,"Aug 4 - Aug 16, 2021",08/04/2021,08/16/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7636,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.2,37,"Sep 1 - Sep 13, 2021",09/01/2021,09/13/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0

In [249]:
### Cómo sería con Estados Unidos, con Wyoming, North Dakota y Hawaii

Filtrar con varias categorías de una misma columna
`.isin()`

In [247]:
df_na[df_na["State"].isin(["Wyoming", "North Dakota", "Hawaii"])]

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
5679,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.1,31,"May 26 - Jun 7, 2021",05/26/2021,06/07/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
6232,Needed Counseling or Therapy But Did Not Get I...,By State,Hawaii,Hawaii,3.1,33,"Jun 23 - Jul 5, 2021",06/23/2021,07/05/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
6836,"Received Counseling or Therapy, Last 4 Weeks",By State,Wyoming,Wyoming,3.2,35,"Aug 4 - Aug 16, 2021",08/04/2021,08/16/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7620,Needed Counseling or Therapy But Did Not Get I...,By State,North Dakota,North Dakota,3.2,37,"Sep 1 - Sep 13, 2021",09/01/2021,09/13/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7636,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.2,37,"Sep 1 - Sep 13, 2021",09/01/2021,09/13/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7780,"Received Counseling or Therapy, Last 4 Weeks",By State,North Dakota,North Dakota,3.2,38,"Sep 15 - Sep 27, 2021",09/15/2021,09/27/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0

In [233]:
df_na[df_na['State'] != 'United States']

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
5674,Needed Counseling or Therapy But Did Not Get I...,By State,Vermont,Vermont,3.1,31,"May 26 - Jun 7, 2021",05/26/2021,06/07/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
5679,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.1,31,"May 26 - Jun 7, 2021",05/26/2021,06/07/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
5970,Needed Counseling or Therapy But Did Not Get I...,By State,Vermont,Vermont,3.1,32,"Jun 9 - Jun 21, 2021",06/09/2021,06/21/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
6232,Needed Counseling or Therapy But Did Not Get I...,By State,Hawaii,Hawaii,3.1,33,"Jun 23 - Jul 5, 2021",06/23/2021,07/05/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
6836,"Received Counseling or Therapy, Last 4 Weeks",By State,Wyoming,Wyoming,3.2,35,"Aug 4 - Aug 16, 2021",08/04/2021,08/16/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7620,Needed Counseling or Therapy But Did Not Get I...,By State,North Dakota,North Dakota,3.2,37,"Sep 1 - Sep 13, 2021",09/01/2021,09/13/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7631,Needed Counseling or Therapy But Did Not Get I...,By State,Vermont,Vermont,3.2,37,"Sep 1 - Sep 13, 2021",09/01/2021,09/13/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7636,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.2,37,"Sep 1 - Sep 13, 2021",09/01/2021,09/13/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0
7780,"Received Counseling or Therapy, Last 4 Weeks",By State,North Dakota,North Dakota,3.2,38,"Sep 15 - Sep 27, 2021",09/15/2021,09/27/2021,NaN,NaN,NaN,NaN,Estimate not reliable.,1.0