# Exploración de Datos (EDA)


# Propedéutico de Programación para el Análisis de datos

## EGobiernoyTP

**Verano 2026**

### Material 5: Exploración de bases de datos: intro pandas

1. Series y DataFrames
   - ¿Qué es una Series?
   - ¿Qué es un DataFrame?
   - Filas, columnas e índice

2. Generalidades de bases de datos
    - ¿Cuántas variables y observaciones tenemos?
    - Diccionario de variables
3. Primera exploración
   - `head()`
   - `tail()`
   - `sample()`
   - `shape`
   - `columns`
   - `info()`
   - `describe()`
4. Seleccionar columnas
   - Una columna
   - Varias columnas
   - Series vs. DataFrame
5. Tipos de datos en db
    - Cambiar tipos de datos
        - str
        - float
        - int
        - datetime



El objetivo de la exploración es aprender a **conocer los datos antes de usarlos**. 

En una base de datos tabular:

- cada fila representa una observación;
  
- cada columna representa una variable;
  
- cada celda contiene un valor.

De las primeras preguntas a responder al tener una base de datos son:

- ¿Cuál es la unidad de observación?

- ¿Cuántas observaciones tenemos?

- ¿Cuántas variables tenemos?

In [5]:
# Librerías 
import pandas as pd
import numpy as np

#### Series y DataFrames

Al trabajar con **pandas** tenemos dos estructuras:

- `Series`: estructura que contiene una secuencia de valores
    - Se puede pensar como una columna de datos
    - Que contiene un índice que identifica las posiciones de las observarciones
- `DataFrame`: estructura de datos organizada con filas y columnas

In [38]:
# Series
edades = pd.Series([25, 34, 29, 41, 22])

edades

0    25
1    34
2    29
3    41
4    22
dtype: int64

In [40]:
# DataFrame
datos = pd.DataFrame({
    "nombre": ["Ana", "Luis", "María", "Carlos", "Sofía"],
    "edad": [25, 34, 29, 41, 22],
    "estado": ["Oaxaca", "Puebla", "Jalisco", "Yucatán", "Oaxaca"],
    "ingreso": [8500, 12000, 10500, 15000, 9000]
})

datos

   nombre  edad   estado  ingreso
0     Ana    25   Oaxaca     8500
1    Luis    34   Puebla    12000
2   María    29  Jalisco    10500
3  Carlos    41  Yucatán    15000
4   Sofía    22   Oaxaca     9000

In [44]:
type(datos)

pandas.DataFrame

In [45]:
type(edades)

pandas.Series

In [48]:
datos['nombre']

0       Ana
1      Luis
2     María
3    Carlos
4     Sofía
Name: nombre, dtype: str

#### Ahora con una base de datos real

In [7]:
#from google.colab import drive
#drive.mount('/content/drive', force_remount=True)

In [8]:
df = pd.read_csv('/content/drive/MyDrive/datos/datos.csv')
#df = pd.read_csv('://raw.githubusercontent.com/ElenaVillano/prope-programacion/refs/heads/main/data/datos.csv')

##### Dimensiones de la base

Es la primera pregunta que nos hacemos: ¿qué tan grande es la base?

`df.shape` regresa una tupla con (número de filas, número de columnas).

In [49]:
df.shape

(10404, 15)

In [50]:
# Columnas
df.shape[1]

15

In [51]:
# Renglones
df.shape[0]

10404

In [52]:
# Nombre de columnas
df.columns

Index(['Indicator', 'Group', 'State', 'Subgroup', 'Phase', 'Time Period',
       'Time Period Label', 'Time Period Start Date', 'Time Period End Date',
       'Value', 'LowCI', 'HighCI', 'Confidence Interval', 'Quartile Range',
       'Suppression Flag'],
      dtype='str')

#### Diccionario de datos

> Antes de analizar una base de datos, debemos entender qué representa cada variable.

- **Fuente:** National Center for Health Statistics (NCHS) + U.S. Census Bureau
- **Qué es:** Encuesta experimental en línea (~20 min) lanzada en abril 2020 por el Census Bureau junto con NCHS y otras agencias federales, para medir en tiempo casi real el impacto de la pandemia de COVID-19 en los hogares estadounidenses.



| Columna | Descripción |
|---|---|
| Indicator | Indicador medido (ej. "Symptoms of Anxiety Disorder") |
| Group | Categoría de desagregación (National Estimate, By Age, By Sex, By State, By Race/Hispanic ethnicity...) |
| State | Estado o "United States" (nacional) |
| Subgroup | Valor específico dentro del Group (ej. "18-29 years") |
| Phase | Fase de la encuesta (1, 2, 3, 3.1...) |
| Time Period | N° secuencial de la ronda de recolección |
| Time Period Label | Rango de fechas legible (ej. "Aug 19 - Aug 31, 2020") |
| Time Period Start Date | Fecha de inicio del periodo |
| Time Period End Date | Fecha de fin del periodo |
| Value | Estimación (%) |
| LowCI | Límite inferior del IC 95% |
| HighCI | Límite superior del IC 95% |
| Confidence Interval | IC en texto (ej. "19.0 - 19.8") |
| Quartile Range | Rango de cuartil (indicadores de vivienda/gasto) |
| Suppression Flag | Marca de supresión por baja fiabilidad estadística |

In [53]:
df.head()

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
0,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Male,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,6.9,6.5,7.3,6.5 - 7.3,NaN,NaN
1,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Female,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,11.0,10.4,11.6,10.4 - 11.6,NaN,NaN
2,Needed Counseling or Therapy But Did Not Get I...,By Sex,United States,Female,-1,1,"Dec 22, 2020 - Jan 5, 2021",12/22/2020,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN
3,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN
4,Took Prescription Medication for Mental Health...,By Age,United States,60 - 69 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN

#### 2. Primera vista: ¿cómo se ven los datos?

`.head()` muestra las primeras filas. Es lo primero que se hace al abrir cualquier base de datos.

In [54]:
df.head(3)

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
0,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Male,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,6.9,6.5,7.3,6.5 - 7.3,NaN,NaN
1,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Female,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,11.0,10.4,11.6,10.4 - 11.6,NaN,NaN
2,Needed Counseling or Therapy But Did Not Get I...,By Sex,United States,Female,-1,1,"Dec 22, 2020 - Jan 5, 2021",12/22/2020,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df.tail()

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
10399,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,Virginia,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,10.1,7.1,13.8,7.1 - 13.8,9.6-11.3,NaN
10400,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,Washington,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,14.8,12.5,17.4,12.5 - 17.4,13.0-20.8,NaN
10401,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,West Virginia,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,9.8,6.6,13.8,6.6 - 13.8,9.6-11.3,NaN
10402,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,Wisconsin,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,11.6,8.5,15.3,8.5 - 15.3,11.4-12.9,NaN
10403,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,Wyoming,3.4,45,"Apr 27 - May 9, 2022",04/27/2022,05/09/2022,11.5,8.6,15.1,8.6 - 15.1,11.4-12.9,NaN

In [56]:
df.sample(10)

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
1624,Took Prescription Medication for Mental Health...,By State,Connecticut,Connecticut,3 (Oct 28 – Dec 21),18,"Oct 28 - Nov 9, 2020",10/28/2020,11/09/2020,28.6,23.7,34.0,23.7 - 34.0,27.1-33.2,NaN
4404,Needed Counseling or Therapy But Did Not Get I...,By State,New York,New York,3 (Jan 6 – Mar 29),27,"Mar 17 - Mar 29, 2021",03/17/2021,03/29/2021,12.6,9.8,15.8,9.8 - 15.8,12.3-14.3,NaN
9707,Needed Counseling or Therapy But Did Not Get I...,By Education,United States,Less than a high school diploma,3.4,43,"Mar 2 - Mar 14, 2022",03/02/2022,03/14/2022,11.7,8.7,15.3,8.7 - 15.3,NaN,NaN
2753,"Received Counseling or Therapy, Last 4 Weeks",By State,Georgia,Georgia,3 (Jan 6 – Mar 29),22,"Jan 6 - Jan 18, 2021",01/06/2021,01/18/2021,7.9,5.4,11.2,5.4 - 11.2,5.0-8.4,NaN
6990,Needed Counseling or Therapy But Did Not Get I...,By State,Utah,Utah,3.2,35,"Aug 4 - Aug 16, 2021",08/04/2021,08/16/2021,13.7,11.1,16.7,11.1 - 16.7,12.1-15.2,NaN
4890,"Received Counseling or Therapy, Last 4 Weeks",By State,Alaska,Alaska,3.1,29,"Apr 28 - May 10, 2021",04/28/2021,05/10/2021,9.7,7.4,12.5,7.4 - 12.5,9.0-9.8,NaN
8582,Took Prescription Medication for Mental Health...,By State,Washington,Washington,3.3,40,"Dec 1 - Dec 13, 2021",12/01/2021,12/13/2021,30.2,27.2,33.3,27.2 - 33.3,27.2-30.3,NaN
9960,Took Prescription Medication for Mental Health...,By State,Delaware,Delaware,3.4,44,"Mar 30 - Apr 11, 2022",03/30/2022,04/11/2022,27.1,20.8,34.1,20.8 - 34.1,25.0-28.5,NaN
2246,Took Prescription Medication for Mental Health...,By State,West Virginia,West Virginia,3 (Oct 28 – Dec 21),20,"Nov 25 - Dec 7, 2020",11/25/2020,12/07/2020,34.8,29.7,40.1,29.7 - 40.1,28.3-34.8,NaN
5057,Needed Counseling or Therapy But Did Not Get I...,By State,Maryland,Maryland,3.1,29,"Apr 28 - May 10, 2021",04/28/2021,05/10/2021,9.8,7.7,12.2,7.7 - 12.2,9.7-11.6,NaN

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10404 entries, 0 to 10403
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Indicator               10404 non-null  str
 1   Group                   10404 non-null  str
 2   State                   10404 non-null  str
 3   Subgroup                10404 non-null  str
 4   Phase                   10404 non-null  str
 5   Time Period             10404 non-null  int64
 6   Time Period Label       10404 non-null  str
 7   Time Period Start Date  10404 non-null  str
 8   Time Period End Date    10404 non-null  str
 9   Value                   9914 non-null   float64
 10  LowCI                   9914 non-null   float64
 11  HighCI                  9914 non-null   float64
 12  Confidence Interval     9914 non-null   str
 13  Quartile Range          6732 non-null   str
 14  Suppression Flag        22 non-null     float64
dtypes: float64(4), int64(1), str(10)
memory usage: 1.2 MB

#### Selección de variables

In [71]:
df['Indicator'].value_counts()

Indicator
Received Counseling or Therapy, Last 4 Weeks                                                          2601
Needed Counseling or Therapy But Did Not Get It, Last 4 Weeks                                         2601
Took Prescription Medication for Mental Health, Last 4 Weeks                                          2601
Took Prescription Medication for Mental Health And/Or Received Counseling or Therapy, Last 4 Weeks    2601
Name: count, dtype: int64

In [68]:
df[['Group','State']]

          Group          State
0        By Sex  United States
1        By Sex  United States
2        By Sex  United States
3        By Age  United States
4        By Age  United States
...         ...            ...
10399  By State       Virginia
10400  By State     Washington
10401  By State  West Virginia
10402  By State      Wisconsin
10403  By State        Wyoming

[10404 rows x 2 columns]

#### 4. Tipos de variables

Determinar el tipo de variables de las columnas determinará en gran medida el análisis de datos.

Cuatro tipos de variables:

| Tipo | Descripción | Ejemplos en esta base |
|---|---|---|
| **Numéricas** | Valores numéricos (enteros o decimales) | `consumo_total`, `latitud` |
| **Categóricas** | Categorías o grupos | `alcaldia`, `indice_des`, `bimestre` |
| **Temporales** | Fechas o periodos de tiempo | `anio`, `bimestre` (combinados) |
| **Texto libre** | Texto sin estructura fija | (no hay en esta base) |

Pandas detecta automáticamente algunos tipos con `.dtypes`:

In [ ]:
# dtypes muestra el tipo de dato que pandas asignó a cada columna
# object = texto,  int64 = entero,  float64 = decimal
df.dtypes

### 4.1 OJO aquí es tu trabajo determinar qué tipo de variables deben de ser

- ¿Cuáles crees que deben de ser categóricas que Python detectó como numéricas?

- ¿Cuáles crees que son categóricas que no deberían de serlo?

In [ ]:
# Variables numéricas: pandas las detecta como int o float
vars_numericas = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Variables categóricas: pandas las detecta como 'object' (texto)
vars_categoricas = df.select_dtypes(include='object').columns.tolist()

print(f'Variables numéricas ({len(vars_numericas)}):  {vars_numericas}')
print()
print(f'Variables categóricas ({len(vars_categoricas)}):  {vars_categoricas}')

In [ ]:
df[vars_categoricas]

In [ ]:
df[vars_numericas]

### 4.2 Cambiar tipos de variables

In [ ]:
df['bimestre'].value_counts()

In [ ]:
# Convert 'bimestre' to string type
df['bimestre_str'] = df['bimestre'].astype(str)

In [ ]:
df

In [ ]:
df['fecha_registro'].value_counts()

In [ ]:
df.dtypes

---
## 6. Data Profiling: Variables Numéricas

El *data profiling* es un resumen detallado de cada variable. Para las numéricas nos interesa saber: ¿cuál es el rango? ¿hay valores extremos? ¿cómo está distribuida?

Vamos a construirlo paso a paso para entender cada estadístico.

In [ ]:
df.describe()

In [ ]:
variables_numericas = ['consumo_total', 'consumo_prom', 'consumo_total_dom', 'consumo_prom_dom', 'consumo_total_no_dom', 'consumo_prom_no_dom', 'consumo_total_mixto', 'consumo_prom_mixto']

In [ ]:
df[variables_numericas].describe()

**¿Qué buscamos en esta tabla?**

- **Media vs. mediana muy diferentes** → indica valores extremos (outliers). Por ejemplo, si la media de `consumo_total` es mucho mayor que la mediana, hay colonias con consumo excepcionalmente alto que "jalan" el promedio hacia arriba.
- **Desviación estándar muy grande** → los datos están muy dispersos.
- **Mínimo = 0** en columnas de consumo → colonias sin consumo registrado.
- **`anio` con desv_estandar = 0** → todos los registros son del mismo año (2019).

---
## 7. Data Profiling: Variables Categóricas

Para variables categóricas nos interesa saber: ¿cuántas categorías hay? ¿cuál es la más frecuente? ¿están balanceadas o muy desiguales?

In [ ]:
# Variables categóricas de interés (quitamos 'colonia' por tener demasiadas categorías)
vars_cat_analisis = ['alcaldia', 'bimestre', 'indice_des','nomgeo']

profiling_cat = pd.DataFrame(index=vars_cat_analisis)

profiling_cat['n_categorias']  = [df[c].nunique() for c in vars_cat_analisis]
profiling_cat['n_faltantes']   = [df[c].isnull().sum() for c in vars_cat_analisis]
profiling_cat['moda']          = [df[c].mode()[0] for c in vars_cat_analisis]
profiling_cat['top_2']         = [df[c].value_counts().index[1] if df[c].nunique() > 1 else '-' for c in vars_cat_analisis]
profiling_cat['top_3']         = [df[c].value_counts().index[2] if df[c].nunique() > 2 else '-' for c in vars_cat_analisis]

profiling_cat

In [ ]:
df['nomgeo'].value_counts()

In [ ]:
df['bimestre'].value_counts()

## 8. Data Profiling: Variables temporales

Lo primero es ver qué tipo de dato tiene pandas asignado a estas columnas.

Si el resultado dice **`object`** — significa que pandas las está tratando como **texto**, no como fechas.

Eso tiene consecuencias importantes:
- **No puedes restarlas** para calcular duración
- **No puedes ordenarlas** correctamente (el orden de texto es alfabético, no cronológico)
- **No puedes graficarlas** en un eje de tiempo

### ¿En qué formato viene la fecha?

Antes de convertir, necesitamos saber el formato. Los más comunes son:

| Ejemplo en los datos | Formato pandas |
|---|---|
| `2021-03-15` | `'%Y-%m-%d'` |
| `15/03/2021` | `'%d/%m/%Y'` |
| `03/15/2021` | `'%m/%d/%Y'` |
| `March 15, 2021` | `'%B %d, %Y'` |
| `15-Mar-2021` | `'%d-%b-%Y'` |

## 8.1. Convertir a datetime — `pd.to_datetime()`

`pd.to_datetime()` es la función de pandas para convertir texto en fechas reales.  
Una vez convertidas, el tipo de dato será **`datetime64[ns]`** — el formato de fecha de pandas.

#### Conversión automática (cuando el formato es estándar)

In [ ]:
df.dtypes

In [ ]:
df['fecha_registro']

In [ ]:
# Si las fechas vienen en formato ISO (YYYY-MM-DD), pandas las detecta solas
# errors='coerce' convierte los valores que no pueda parsear en NaT (Not a Time)
# en lugar de lanzar un error — útil para detectar fechas mal formateadas
df['fecha_registro_date'] = pd.to_datetime(df['fecha_registro'], errors='coerce')

In [ ]:
df.dtypes

In [ ]:
print("--- Rango de Fechas ---")
min_date = df['fecha_registro_date'].min()
max_date = df['fecha_registro_date'].max()
print(f"Fecha mínima: {min_date}")
print(f"Fecha máxima: {max_date}")


### 8.2 Extraer componentes de la fecha

Una vez que la columna es `datetime`, podemos extraer partes de la fecha con el **accessor `.dt`**.  
Es como abrir la fecha y sacar lo que nos interesa.

| Accessor | Qué devuelve | Rango típico |
|---|---|---|
| `.dt.year` | Año | 2015, 2016... |
| `.dt.month` | Número de mes | 1–12 |
| `.dt.month_name()` | Nombre del mes | 'January'... |
| `.dt.day` | Día del mes | 1–31 |
| `.dt.day_of_week` | Día de la semana | 0=lunes, 6=domingo |
| `.dt.day_name()` | Nombre del día | 'Monday'... |
| `.dt.quarter` | Trimestre | 1–4 |
| `.dt.is_month_start` | ¿Es el primer día del mes? | True/False |

In [ ]:
# Extraemos componentes útiles de la fecha de inicio
df['anio_inicio']     = df['fecha_registro_date'].dt.year
df['mes_inicio']      = df['fecha_registro_date'].dt.month
df['nombre_mes']      = df['fecha_registro_date'].dt.month_name()  # Nombre en inglés
df['trimestre']       = df['fecha_registro_date'].dt.quarter
df['dia_semana']      = df['fecha_registro_date'].dt.day_name()

# Vista de los nuevos componentes
df[['fecha_registro_date', 'anio_inicio', 'mes_inicio', 'nombre_mes', 'trimestre', 'dia_semana']].head(8)

In [ ]:
df['mes_inicio'].value_counts()