[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ElenaVillano/prope-programacion/blob/main/materiales/m06_mas_exploracion.ipynb)

# Propedéutico de Programación para el Análisis de datos

## EGobiernoyTP

**Verano 2026**

### Material 6: Exploración de bases de datos: intro pandas

In [3]:
# Librerías 
import pandas as pd
import numpy as np

#### Ahora con una base de datos real

In [2]:
#from google.colab import drive
#drive.mount('/content/drive', force_remount=True)

In [98]:
#df = pd.read_csv('/content/drive/MyDrive/datos/datos.csv')
df = pd.read_csv('https://raw.githubusercontent.com/ElenaVillano/prope-programacion/refs/heads/main/data/datos.csv')

In [99]:
df.head()

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
0,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Male,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,6.9,6.5,7.3,6.5 - 7.3,NaN,NaN
1,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Female,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,11.0,10.4,11.6,10.4 - 11.6,NaN,NaN
2,Needed Counseling or Therapy But Did Not Get I...,By Sex,United States,Female,-1,1,"Dec 22, 2020 - Jan 5, 2021",12/22/2020,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN
3,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN
4,Took Prescription Medication for Mental Health...,By Age,United States,60 - 69 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN

Trabajemos con la base de datos más limpia

In [100]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [101]:
df.head()

,indicator,group,state,subgroup,phase,time_period,time_period_label,time_period_start_date,time_period_end_date,value,lowci,highci,confidence_interval,quartile_range,suppression_flag
0,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Male,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,6.9,6.5,7.3,6.5 - 7.3,NaN,NaN
1,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Female,2,15,"Sep 16 - Sep 28, 2020",09/16/2020,09/28/2020,11.0,10.4,11.6,10.4 - 11.6,NaN,NaN
2,Needed Counseling or Therapy But Did Not Get I...,By Sex,United States,Female,-1,1,"Dec 22, 2020 - Jan 5, 2021",12/22/2020,01/05/2021,NaN,NaN,NaN,NaN,NaN,NaN
3,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN
4,Took Prescription Medication for Mental Health...,By Age,United States,60 - 69 years,-1,1,"Mar 30 - Apr 13, 2021",03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN,NaN

Si solo quieres renombrar una columna

In [102]:
df = df.rename(columns={"lowci": "low_ci", "highci": "high_ci" })

### 7. Subconjuntos de base de datos

- Quitando columnas

In [103]:
df.drop(['confidence_interval',
         'time_period_label'], 
        axis=1, # 0 es por filas y 1 por columnas.
        inplace=True # True es para guardar los cambios sobre la misma base. 
       )

In [104]:
df.head()

,indicator,group,state,subgroup,phase,time_period,time_period_start_date,time_period_end_date,value,low_ci,high_ci,quartile_range,suppression_flag
0,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Male,2,15,09/16/2020,09/28/2020,6.9,6.5,7.3,NaN,NaN
1,"Received Counseling or Therapy, Last 4 Weeks",By Sex,United States,Female,2,15,09/16/2020,09/28/2020,11.0,10.4,11.6,NaN,NaN
2,Needed Counseling or Therapy But Did Not Get I...,By Sex,United States,Female,-1,1,12/22/2020,01/05/2021,NaN,NaN,NaN,NaN,NaN
3,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,-1,1,03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN
4,Took Prescription Medication for Mental Health...,By Age,United States,60 - 69 years,-1,1,03/30/2021,04/13/2021,NaN,NaN,NaN,NaN,NaN

Si sólo quieres reodenar columnas o seleccionar unas pocas:

In [105]:
df = df[
    ["state", "indicator", "group", "subgroup", "low_ci","value", "high_ci","time_period_start_date", "time_period_end_date"]
]

In [106]:
df.head()

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date
0,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Male,6.5,6.9,7.3,09/16/2020,09/28/2020
1,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Female,10.4,11.0,11.6,09/16/2020,09/28/2020
2,United States,Needed Counseling or Therapy But Did Not Get I...,By Sex,Female,NaN,NaN,NaN,12/22/2020,01/05/2021
3,United States,Took Prescription Medication for Mental Health...,By Age,50 - 59 years,NaN,NaN,NaN,03/30/2021,04/13/2021
4,United States,Took Prescription Medication for Mental Health...,By Age,60 - 69 years,NaN,NaN,NaN,03/30/2021,04/13/2021

### Seleccionar un subconjunto basado en una condición

Por ejemplo, quedarnos únicamente con las observaciones de Vermont:

In [107]:
df_vermont = df[df["state"] == "Vermont"]

df_vermont.head()

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date
79,Vermont,Took Prescription Medication for Mental Health...,By State,Vermont,18.5,23.2,28.5,08/19/2020,08/31/2020
151,Vermont,"Received Counseling or Therapy, Last 4 Weeks",By State,Vermont,8.8,11.4,14.5,08/19/2020,08/31/2020
223,Vermont,Took Prescription Medication for Mental Health...,By State,Vermont,22.5,27.8,33.6,08/19/2020,08/31/2020
295,Vermont,Needed Counseling or Therapy But Did Not Get I...,By State,Vermont,7.2,10.5,14.7,08/19/2020,08/31/2020
367,Vermont,Took Prescription Medication for Mental Health...,By State,Vermont,18.9,22.3,26.1,09/02/2020,09/14/2020

In [108]:
df_vermont.shape

(132, 9)

In [109]:
## Construir condición

### Comparaciones numéricas

Por ejemplo, observaciones cuyo valor sea mayor a 40:

In [110]:
df['value'].dtype

dtype('float64')

In [111]:
df['value'].max()

np.float64(62.9)

In [112]:
df['value'].min()

np.float64(1.4)

In [113]:
df['value'].describe()

count    9914.000000
mean       17.450736
std         8.270565
min         1.400000
25%        10.300000
50%        16.200000
75%        24.000000
max        62.900000
Name: value, dtype: float64

In [114]:
df['value'].quantile(0.95)

np.float64(30.1)

In [115]:
q99 = df['value'].quantile(0.99)

In [116]:
dfq99 = df[df["value"] > q99 ]

In [117]:
dfq99.shape

(98, 9)

U obtener valores dentro de cierto rango:

In [118]:
df[
    (df["value"] >= 40) &
    (df["value"] <= 60)
].head()

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date
4000,United States,Took Prescription Medication for Mental Health...,By Presence of Symptoms of Anxiety/Depression,Experienced symptoms of anxiety/depression in ...,39.5,41.0,42.6,03/03/2021,03/15/2021
4455,United States,Took Prescription Medication for Mental Health...,By Disability status,With disability,39.1,41.3,43.6,04/14/2021,04/26/2021
4634,United States,Took Prescription Medication for Mental Health...,By Presence of Symptoms of Anxiety/Depression,Experienced symptoms of anxiety/depression in ...,39.6,41.3,43.0,04/14/2021,04/26/2021
4645,United States,Took Prescription Medication for Mental Health...,By Disability status,With disability,42.9,45.0,47.2,04/14/2021,04/26/2021
4813,United States,Took Prescription Medication for Mental Health...,By Disability status,With disability,43.7,45.7,47.6,04/28/2021,05/10/2021

Recordemos sintaxis:

```
&   y
|   o
~   negación
```

### Seleccionando subconjuntos de la base

`.loc` permite seleccionar filas y columnas al mismo tiempo.

La estructura general es:

```
df.loc[filas, columnas]
```

In [119]:
df.loc[df["state"] == "Vermont",["state", "indicator", "value"]]

         state                                          indicator  value
79     Vermont  Took Prescription Medication for Mental Health...   23.2
151    Vermont       Received Counseling or Therapy, Last 4 Weeks   11.4
223    Vermont  Took Prescription Medication for Mental Health...   27.8
295    Vermont  Needed Counseling or Therapy But Did Not Get I...   10.5
367    Vermont  Took Prescription Medication for Mental Health...   22.3
...        ...                                                ...    ...
10078  Vermont  Needed Counseling or Therapy But Did Not Get I...    8.3
10158  Vermont  Took Prescription Medication for Mental Health...   25.2
10238  Vermont       Received Counseling or Therapy, Last 4 Weeks    9.9
10318  Vermont  Took Prescription Medication for Mental Health...   27.9
10398  Vermont  Needed Counseling or Therapy But Did Not Get I...   11.9

[132 rows x 3 columns]

In [120]:
df.loc[df["value"] > 40, ["state", "indicator","subgroup", "value"]]

,state,indicator,subgroup,value
4000,United States,Took Prescription Medication for Mental Health...,Experienced symptoms of anxiety/depression in ...,41.0
4455,United States,Took Prescription Medication for Mental Health...,With disability,41.3
4634,United States,Took Prescription Medication for Mental Health...,Experienced symptoms of anxiety/depression in ...,41.3
4645,United States,Took Prescription Medication for Mental Health...,With disability,45.0
4813,United States,Took Prescription Medication for Mental Health...,With disability,45.7
...,...,...,...,...
10256,United States,Took Prescription Medication for Mental Health...,Transgender,57.3
10257,United States,Took Prescription Medication for Mental Health...,Gay or lesbian,41.0
10259,United States,Took Prescription Medication for Mental Health...,Bisexual,46.0
10261,United States,Took Prescription Medication for Mental Health...,Experienced symptoms of anxiety/depression in ...,44.7
10271,United States,Took Prescription Medication for Mental Health...,With disability,46.4

### `iloc` 

Mientras `loc` trabaja principalmente con nombres y condiciones, `iloc` selecciona por posición.

Primeras 5 filas y primeras 4 columnas:

In [121]:
df.iloc[:5, :4]

,state,indicator,group,subgroup
0,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Male
1,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Female
2,United States,Needed Counseling or Therapy But Did Not Get I...,By Sex,Female
3,United States,Took Prescription Medication for Mental Health...,By Age,50 - 59 years
4,United States,Took Prescription Medication for Mental Health...,By Age,60 - 69 years

In [122]:
# Selecciona las filas 2 hasta la 6
df.iloc[2:6,]

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date
2,United States,Needed Counseling or Therapy But Did Not Get I...,By Sex,Female,NaN,NaN,NaN,12/22/2020,01/05/2021
3,United States,Took Prescription Medication for Mental Health...,By Age,50 - 59 years,NaN,NaN,NaN,03/30/2021,04/13/2021
4,United States,Took Prescription Medication for Mental Health...,By Age,60 - 69 years,NaN,NaN,NaN,03/30/2021,04/13/2021
5,United States,Took Prescription Medication for Mental Health...,By Age,70 - 79 years,NaN,NaN,NaN,03/30/2021,04/13/2021

In [123]:
df.iloc[:,[2,4,6]]

          group  low_ci  high_ci
0        By Sex     6.5      7.3
1        By Sex    10.4     11.6
2        By Sex     NaN      NaN
3        By Age     NaN      NaN
4        By Age     NaN      NaN
...         ...     ...      ...
10399  By State     7.1     13.8
10400  By State    12.5     17.4
10401  By State     6.6     13.8
10402  By State     8.5     15.3
10403  By State     8.6     15.1

[10404 rows x 3 columns]

Para análisis de datos normalmente utilizaremos más `loc`, porque los nombres de las variables hacen el código más fácil de leer.

### Ordenar datos

Podemos ordenar las observaciones con sort_values().

In [124]:
# Orden ascendente
df.sort_values("value")

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date
3634,United States,"Received Counseling or Therapy, Last 4 Weeks",By Age,80 years and above,0.9,1.4,2.1,02/17/2021,03/01/2021
236,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,0.9,1.4,2.0,08/19/2020,08/31/2020
6206,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,0.8,1.8,3.5,06/23/2021,07/05/2021
10171,United States,"Received Counseling or Therapy, Last 4 Weeks",By Age,80 years and above,1.3,2.0,3.0,04/27/2022,05/09/2022
6924,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,1.2,2.1,3.2,08/04/2021,08/16/2021
...,...,...,...,...,...,...,...,...,...
9680,United States,Needed Counseling or Therapy But Did Not Get I...,By Education,Some college/Associate's degree,NaN,NaN,NaN,02/23/2022,03/01/2022
9681,United States,Needed Counseling or Therapy But Did Not Get I...,By Education,Bachelor's degree or higher,NaN,NaN,NaN,02/23/2022,03/01/2022
9682,United States,Needed Counseling or Therapy But Did Not Get I...,By Disability status,With disability,NaN,NaN,NaN,02/23/2022,03/01/2022
9683,United States,Needed Counseling or Therapy But Did Not Get I...,By Disability status,Without disability,NaN,NaN,NaN,02/23/2022,03/01/2022
10011,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,NaN,NaN,NaN,03/30/2022,04/11/2022

In [125]:
# Orden ascendente
df.sort_values("value", ascending=False)

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date
6849,United States,Took Prescription Medication for Mental Health...,By Gender identity,Transgender,53.2,62.9,71.9,08/04/2021,08/16/2021
9181,United States,Took Prescription Medication for Mental Health...,By Gender identity,Transgender,49.2,60.1,70.2,01/26/2022,02/07/2022
10256,United States,Took Prescription Medication for Mental Health...,By Gender identity,Transgender,44.0,57.3,69.8,04/27/2022,05/09/2022
6506,United States,Took Prescription Medication for Mental Health...,By Gender identity,Transgender,43.9,56.6,68.7,07/21/2021,08/02/2021
7809,United States,Took Prescription Medication for Mental Health...,By Gender identity,Transgender,45.7,56.0,65.9,09/15/2021,09/27/2021
...,...,...,...,...,...,...,...,...,...
9680,United States,Needed Counseling or Therapy But Did Not Get I...,By Education,Some college/Associate's degree,NaN,NaN,NaN,02/23/2022,03/01/2022
9681,United States,Needed Counseling or Therapy But Did Not Get I...,By Education,Bachelor's degree or higher,NaN,NaN,NaN,02/23/2022,03/01/2022
9682,United States,Needed Counseling or Therapy But Did Not Get I...,By Disability status,With disability,NaN,NaN,NaN,02/23/2022,03/01/2022
9683,United States,Needed Counseling or Therapy But Did Not Get I...,By Disability status,Without disability,NaN,NaN,NaN,02/23/2022,03/01/2022
10011,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,NaN,NaN,NaN,03/30/2022,04/11/2022

### Ordenar por más de una variable

In [126]:
df.sort_values(["indicator", "value"],
               # ascending = [True,False]
              )

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date
236,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,0.9,1.4,2.0,08/19/2020,08/31/2020
6206,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,0.8,1.8,3.5,06/23/2021,07/05/2021
6924,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,1.2,2.1,3.2,08/04/2021,08/16/2021
1099,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,1.1,2.3,4.2,09/30/2020,10/12/2020
8204,United States,Needed Counseling or Therapy But Did Not Get I...,By Age,80 years and above,1.3,2.3,3.6,09/29/2021,10/11/2021
...,...,...,...,...,...,...,...,...,...
9352,United States,Took Prescription Medication for Mental Health...,By Education,High school diploma or GED,NaN,NaN,NaN,02/23/2022,03/01/2022
9353,United States,Took Prescription Medication for Mental Health...,By Education,Some college/Associate's degree,NaN,NaN,NaN,02/23/2022,03/01/2022
9354,United States,Took Prescription Medication for Mental Health...,By Education,Bachelor's degree or higher,NaN,NaN,NaN,02/23/2022,03/01/2022
9355,United States,Took Prescription Medication for Mental Health...,By Disability status,With disability,NaN,NaN,NaN,02/23/2022,03/01/2022
9356,United States,Took Prescription Medication for Mental Health...,By Disability status,Without disability,NaN,NaN,NaN,02/23/2022,03/01/2022

### Crear y modificar variables

In [127]:
df["nueva_variable"] = ...

In [128]:
df.dtypes

state                         str
indicator                     str
group                         str
subgroup                      str
low_ci                    float64
value                     float64
high_ci                   float64
time_period_start_date        str
time_period_end_date          str
nueva_variable             object
dtype: object

Para trabajar sobre una nueva

In [129]:
df_ejemplo = df.copy()

In [131]:
df_ejemplo

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date,nueva_variable
0,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Male,6.5,6.9,7.3,09/16/2020,09/28/2020,Ellipsis
1,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Female,10.4,11.0,11.6,09/16/2020,09/28/2020,Ellipsis
2,United States,Needed Counseling or Therapy But Did Not Get I...,By Sex,Female,NaN,NaN,NaN,12/22/2020,01/05/2021,Ellipsis
3,United States,Took Prescription Medication for Mental Health...,By Age,50 - 59 years,NaN,NaN,NaN,03/30/2021,04/13/2021,Ellipsis
4,United States,Took Prescription Medication for Mental Health...,By Age,60 - 69 years,NaN,NaN,NaN,03/30/2021,04/13/2021,Ellipsis
...,...,...,...,...,...,...,...,...,...,...
10399,Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,7.1,10.1,13.8,04/27/2022,05/09/2022,Ellipsis
10400,Washington,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,12.5,14.8,17.4,04/27/2022,05/09/2022,Ellipsis
10401,West Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,6.6,9.8,13.8,04/27/2022,05/09/2022,Ellipsis
10402,Wisconsin,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,8.5,11.6,15.3,04/27/2022,05/09/2022,Ellipsis
10403,Wyoming,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,8.6,11.5,15.1,04/27/2022,05/09/2022,Ellipsis

In [136]:
df_ejemplo["amplitud_ic"] = (df_ejemplo["high_ci"] - df_ejemplo["low_ci"])

df_ejemplo[["low_ci", "high_ci", "amplitud_ic"]].sample(10)

      low_ci  high_ci  amplitud_ic
887     32.2     34.5          2.3
3452    23.5     33.1          9.6
5885    21.8     29.9          8.1
7333    14.6     15.9          1.3
4287    14.9     16.4          1.5
4691    25.6     34.4          8.8
6322    42.0     46.6          4.6
650     18.3     24.6          6.3
5115    13.8     17.5          3.7
7416    10.6     11.5          0.9

In [139]:
# Todas las comparaciones que realices se pueden convertir en variables
df_ejemplo["valor_mayor_50"] = (
    df_ejemplo["value"] > 50
)

df_ejemplo[
    ["value", "valor_mayor_50"]
].head()

   value  valor_mayor_50
0    6.9           False
1   11.0           False
2    NaN           False
3    NaN           False
4    NaN           False

In [141]:
# Podemos crear una variable que indique si pertenece a ciertos estados:
df_ejemplo["estado_seleccionado"] = (
    df_ejemplo["state"]
    .isin(["Wyoming", "North Dakota", "Hawaii"])
)

In [143]:
df_ejemplo.head()

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date,nueva_variable,amplitud_ic,valor_mayor_50,estado_seleccionado
0,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Male,6.5,6.9,7.3,09/16/2020,09/28/2020,Ellipsis,0.8,False,False
1,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Female,10.4,11.0,11.6,09/16/2020,09/28/2020,Ellipsis,1.2,False,False
2,United States,Needed Counseling or Therapy But Did Not Get I...,By Sex,Female,NaN,NaN,NaN,12/22/2020,01/05/2021,Ellipsis,NaN,False,False
3,United States,Took Prescription Medication for Mental Health...,By Age,50 - 59 years,NaN,NaN,NaN,03/30/2021,04/13/2021,Ellipsis,NaN,False,False
4,United States,Took Prescription Medication for Mental Health...,By Age,60 - 69 years,NaN,NaN,NaN,03/30/2021,04/13/2021,Ellipsis,NaN,False,False

### Operaciones básicas con texto

In [144]:
df_ejemplo["state_lower"] = (
    df_ejemplo["state"].str.lower()
)

df_ejemplo[
    ["state", "state_lower"]
].head()

           state    state_lower
0  United States  united states
1  United States  united states
2  United States  united states
3  United States  united states
4  United States  united states

In [145]:
df_ejemplo["state_upper"] = (
    df_ejemplo["state"].str.upper()
)

In [153]:
df_ejemplo[
    df_ejemplo["indicator"]
    .str.contains("Counseling", 
                  case=False)]

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date,nueva_variable,amplitud_ic,valor_mayor_50,estado_seleccionado,state_lower,state_upper
0,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Male,6.5,6.9,7.3,09/16/2020,09/28/2020,Ellipsis,0.8,False,False,united states,UNITED STATES
1,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Female,10.4,11.0,11.6,09/16/2020,09/28/2020,Ellipsis,1.2,False,False,united states,UNITED STATES
2,United States,Needed Counseling or Therapy But Did Not Get I...,By Sex,Female,NaN,NaN,NaN,12/22/2020,01/05/2021,Ellipsis,NaN,False,False,united states,UNITED STATES
9,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Female,NaN,NaN,NaN,03/30/2021,04/13/2021,Ellipsis,NaN,False,False,united states,UNITED STATES
10,United States,"Received Counseling or Therapy, Last 4 Weeks",By Age,40 - 49 years,NaN,NaN,NaN,07/06/2021,07/20/2021,Ellipsis,NaN,False,False,united states,UNITED STATES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10399,Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,7.1,10.1,13.8,04/27/2022,05/09/2022,Ellipsis,6.7,False,False,virginia,VIRGINIA
10400,Washington,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,12.5,14.8,17.4,04/27/2022,05/09/2022,Ellipsis,4.9,False,False,washington,WASHINGTON
10401,West Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,6.6,9.8,13.8,04/27/2022,05/09/2022,Ellipsis,7.2,False,False,west virginia,WEST VIRGINIA
10402,Wisconsin,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,8.5,11.6,15.3,04/27/2022,05/09/2022,Ellipsis,6.8,False,False,wisconsin,WISCONSIN
10403,Wyoming,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,8.6,11.5,15.1,04/27/2022,05/09/2022,Ellipsis,6.5,False,True,wyoming,WYOMING

### Índice y `reset_index()`
Cada DataFrame tiene un índice:

In [157]:
df.index

RangeIndex(start=0, stop=10404, step=1)

In [158]:
df['indicator'].index

RangeIndex(start=0, stop=10404, step=1)

In [159]:
df.head()

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date,nueva_variable
0,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Male,6.5,6.9,7.3,09/16/2020,09/28/2020,Ellipsis
1,United States,"Received Counseling or Therapy, Last 4 Weeks",By Sex,Female,10.4,11.0,11.6,09/16/2020,09/28/2020,Ellipsis
2,United States,Needed Counseling or Therapy But Did Not Get I...,By Sex,Female,NaN,NaN,NaN,12/22/2020,01/05/2021,Ellipsis
3,United States,Took Prescription Medication for Mental Health...,By Age,50 - 59 years,NaN,NaN,NaN,03/30/2021,04/13/2021,Ellipsis
4,United States,Took Prescription Medication for Mental Health...,By Age,60 - 69 years,NaN,NaN,NaN,03/30/2021,04/13/2021,Ellipsis

In [160]:
df_vermont = df[df["state"] == "Vermont"]

df_vermont.head()

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date,nueva_variable
79,Vermont,Took Prescription Medication for Mental Health...,By State,Vermont,18.5,23.2,28.5,08/19/2020,08/31/2020,Ellipsis
151,Vermont,"Received Counseling or Therapy, Last 4 Weeks",By State,Vermont,8.8,11.4,14.5,08/19/2020,08/31/2020,Ellipsis
223,Vermont,Took Prescription Medication for Mental Health...,By State,Vermont,22.5,27.8,33.6,08/19/2020,08/31/2020,Ellipsis
295,Vermont,Needed Counseling or Therapy But Did Not Get I...,By State,Vermont,7.2,10.5,14.7,08/19/2020,08/31/2020,Ellipsis
367,Vermont,Took Prescription Medication for Mental Health...,By State,Vermont,18.9,22.3,26.1,09/02/2020,09/14/2020,Ellipsis

In [161]:
df['state'].unique()

<StringArray>
[       'United States',              'Alabama',               'Alaska',
              'Arizona',             'Arkansas',           'California',
             'Colorado',          'Connecticut',             'Delaware',
 'District of Columbia',              'Florida',              'Georgia',
               'Hawaii',                'Idaho',             'Illinois',
              'Indiana',                 'Iowa',               'Kansas',
             'Kentucky',            'Louisiana',                'Maine',
             'Maryland',        'Massachusetts',             'Michigan',
            'Minnesota',          'Mississippi',             'Missouri',
              'Montana',             'Nebraska',               'Nevada',
        'New Hampshire',           'New Jersey',           'New Mexico',
             'New York',       'North Carolina',         'North Dakota',
                 'Ohio',             'Oklahoma',               'Oregon',
         'Pennsylvania',         'Rhode Island',       'South Carolina',
         'South Dakota',            'Tennessee',                'Texas',
                 'Utah',              'Vermont',             'Virginia',
           'Washington',        'West Virginia',            'Wisconsin',
              'Wyoming']
Length: 52, dtype: str

In [173]:
# seleccionar solo las categorias que tienen corredor y autopista
df_estados = df[df['state']!= "United States"]

In [174]:
df_estados

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date,nueva_variable
34,Alabama,Took Prescription Medication for Mental Health...,By State,Alabama,19.6,22.3,25.1,08/19/2020,08/31/2020,Ellipsis
35,Alaska,Took Prescription Medication for Mental Health...,By State,Alaska,14.2,16.7,19.5,08/19/2020,08/31/2020,Ellipsis
36,Arizona,Took Prescription Medication for Mental Health...,By State,Arizona,16.1,18.3,20.7,08/19/2020,08/31/2020,Ellipsis
37,Arkansas,Took Prescription Medication for Mental Health...,By State,Arkansas,20.8,24.1,27.7,08/19/2020,08/31/2020,Ellipsis
38,California,Took Prescription Medication for Mental Health...,By State,California,14.4,15.8,17.4,08/19/2020,08/31/2020,Ellipsis
...,...,...,...,...,...,...,...,...,...,...
10399,Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,7.1,10.1,13.8,04/27/2022,05/09/2022,Ellipsis
10400,Washington,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,12.5,14.8,17.4,04/27/2022,05/09/2022,Ellipsis
10401,West Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,6.6,9.8,13.8,04/27/2022,05/09/2022,Ellipsis
10402,Wisconsin,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,8.5,11.6,15.3,04/27/2022,05/09/2022,Ellipsis
10403,Wyoming,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,8.6,11.5,15.1,04/27/2022,05/09/2022,Ellipsis

In [178]:
# Hace un drop del index sin conservarlo
df_estados.reset_index(drop=True)

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date,nueva_variable
0,Alabama,Took Prescription Medication for Mental Health...,By State,Alabama,19.6,22.3,25.1,08/19/2020,08/31/2020,Ellipsis
1,Alaska,Took Prescription Medication for Mental Health...,By State,Alaska,14.2,16.7,19.5,08/19/2020,08/31/2020,Ellipsis
2,Arizona,Took Prescription Medication for Mental Health...,By State,Arizona,16.1,18.3,20.7,08/19/2020,08/31/2020,Ellipsis
3,Arkansas,Took Prescription Medication for Mental Health...,By State,Arkansas,20.8,24.1,27.7,08/19/2020,08/31/2020,Ellipsis
4,California,Took Prescription Medication for Mental Health...,By State,California,14.4,15.8,17.4,08/19/2020,08/31/2020,Ellipsis
...,...,...,...,...,...,...,...,...,...,...
6727,Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,7.1,10.1,13.8,04/27/2022,05/09/2022,Ellipsis
6728,Washington,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,12.5,14.8,17.4,04/27/2022,05/09/2022,Ellipsis
6729,West Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,6.6,9.8,13.8,04/27/2022,05/09/2022,Ellipsis
6730,Wisconsin,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,8.5,11.6,15.3,04/27/2022,05/09/2022,Ellipsis
6731,Wyoming,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,8.6,11.5,15.1,04/27/2022,05/09/2022,Ellipsis

In [176]:
df_estados.reset_index(inplace=True,drop=True)

In [177]:
df_estados

,state,indicator,group,subgroup,low_ci,value,high_ci,time_period_start_date,time_period_end_date,nueva_variable
0,Alabama,Took Prescription Medication for Mental Health...,By State,Alabama,19.6,22.3,25.1,08/19/2020,08/31/2020,Ellipsis
1,Alaska,Took Prescription Medication for Mental Health...,By State,Alaska,14.2,16.7,19.5,08/19/2020,08/31/2020,Ellipsis
2,Arizona,Took Prescription Medication for Mental Health...,By State,Arizona,16.1,18.3,20.7,08/19/2020,08/31/2020,Ellipsis
3,Arkansas,Took Prescription Medication for Mental Health...,By State,Arkansas,20.8,24.1,27.7,08/19/2020,08/31/2020,Ellipsis
4,California,Took Prescription Medication for Mental Health...,By State,California,14.4,15.8,17.4,08/19/2020,08/31/2020,Ellipsis
...,...,...,...,...,...,...,...,...,...,...
6727,Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,Virginia,7.1,10.1,13.8,04/27/2022,05/09/2022,Ellipsis
6728,Washington,Needed Counseling or Therapy But Did Not Get I...,By State,Washington,12.5,14.8,17.4,04/27/2022,05/09/2022,Ellipsis
6729,West Virginia,Needed Counseling or Therapy But Did Not Get I...,By State,West Virginia,6.6,9.8,13.8,04/27/2022,05/09/2022,Ellipsis
6730,Wisconsin,Needed Counseling or Therapy But Did Not Get I...,By State,Wisconsin,8.5,11.6,15.3,04/27/2022,05/09/2022,Ellipsis
6731,Wyoming,Needed Counseling or Therapy But Did Not Get I...,By State,Wyoming,8.6,11.5,15.1,04/27/2022,05/09/2022,Ellipsis

### Agrupación

Seguramente todos han usado tablas dinámicas antes, por ejemplo, para obtener el promedio de una variable para cada una de las categorías existentes en los datos. 

En realidad, las operaciones que están realizando para obtener estos npumeros son _agrupar_ y después _agregar_ con alguna función, que puede ser suma, promedio, máximo, mínimo, etc. Entonces, para escribirlo en python, usaremos `groupby` y las funciones relacionadas a cada una de esas operaciones (e.g. `min()` , `mean()` , `median()` , `count()`, `std()`)

Por ejemplo, utilicemos la variable de región que creamos hace unas líneas, y obtengamos algunos estadísticos para varaibles interesantes.